services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
      args:
        - ENVIRONMENT=local
    volumes:
      - .:/app:z
      - /app/.venv/  # Exclude venv directory from mounting
    ports:
      - '8000:8000'
    command: /start
