"""auto

Revision ID: 000004
Revises: 000003
Create Date: 2025-07-15 16:51:49.436264

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "000004"
down_revision: Union[str, None] = "000003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("turn")
    op.drop_column("connection", "is_host")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "connection",
        sa.Column("is_host", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.create_table(
        "turn",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM("PHOTO_ROAST", name="turntype"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "phase",
            postgresql.ENUM(
                "SETUP", "PROCESSING", "INTERACTION", "RESULTS", name="turnphase"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("game_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["game_id"], ["game.id"], name="turn_game_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="turn_pkey"),
        sa.UniqueConstraint(
            "game_id",
            "count",
            name="turn_game_id_count_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
