"""Add PostgreSQL LISTEN/NOTIFY triggers for Connection model

Revision ID: 000002
Revises: 000001
Create Date: 2025-07-15 13:29:26.795224

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "000002"
down_revision: Union[str, None] = "000001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

    # Create PostgreSQL NOTIFY functions for Connection model
    op.execute("""
        CREATE OR REPLACE FUNCTION notify_game_change() RETURNS TRIGGER AS $$
        BEGIN
            -- Notify on connection changes (join, leave, heartbeat)
            IF TG_TABLE_NAME = 'connection' THEN
                IF TG_OP = 'DELETE' THEN
                    PERFORM pg_notify('game_change', (SELECT code FROM game WHERE id = OLD.game_id));
                    RETURN OLD;
                ELSIF TG_OP = 'INSERT' THEN
                    PERFORM pg_notify('game_change', (SELECT code FROM game WHERE id = NEW.game_id));
                    RETURN NEW;
                ELSIF TG_OP = 'UPDATE' THEN
                    -- Only notify if is_active changed
                    IF OLD.is_active IS DISTINCT FROM NEW.is_active THEN
                        PERFORM pg_notify('game_change', (SELECT code FROM game WHERE id = NEW.game_id));
                    END IF;
                    RETURN NEW;
                END IF;
            END IF;
            
            -- Notify on game changes (status, host changes)
            IF TG_TABLE_NAME = 'game' THEN
                PERFORM pg_notify('game_change', NEW.code);
                RETURN NEW;
            END IF;
            
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # Create triggers for connection changes
    op.execute("""
        CREATE TRIGGER connection_change_trigger
        AFTER INSERT OR UPDATE OR DELETE ON connection
        FOR EACH ROW
        EXECUTE FUNCTION notify_game_change();
    """)

    # Create triggers for game changes
    op.execute("""
        CREATE TRIGGER game_change_trigger
        AFTER INSERT OR UPDATE ON game
        FOR EACH ROW
        EXECUTE FUNCTION notify_game_change();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Drop triggers and functions first
    op.execute("DROP TRIGGER IF EXISTS connection_change_trigger ON connection;")
    op.execute("DROP TRIGGER IF EXISTS game_change_trigger ON game;")
    op.execute("DROP FUNCTION IF EXISTS notify_game_change();")

    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
