"""Rename is_connected to is_active in Connection model

Revision ID: 000003
Revises: 000002
Create Date: 2025-07-15 13:34:01.726769

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "000003"
down_revision: Union[str, None] = "000002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("connection", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.drop_column("connection", "is_connected")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "connection",
        sa.Column("is_connected", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("connection", "is_active")
    # ### end Alembic commands ###
