"""Add activity_changed_at to PlayerConnection

Revision ID: 000005
Revises: 000004
Create Date: 2025-07-16 06:38:14.162380

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "000005"
down_revision: Union[str, None] = "000004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column(
        "connection", sa.Column("activity_changed_at", sa.DateTime(), nullable=True)
    )

    # Set default value for existing rows (use created_at as initial value)
    op.execute(
        "UPDATE connection SET activity_changed_at = created_at WHERE activity_changed_at IS NULL"
    )

    # Make column NOT NULL
    op.alter_column("connection", "activity_changed_at", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("connection", "activity_changed_at")
    # ### end Alembic commands ###
