#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


# Common
# --------------------------------------------------
python manage.py migrate
python manage.py collectstatic --noinput --clear


if [ "$ENVIRONMENT" = "local" ]; then
    # Local
    # --------------------------------------------------

    echo "Running in local development mode"

    # uvicorn w/ auto-reload
    exec uvicorn config.asgi:application --host 0.0.0.0 --reload

elif [ "$ENVIRONMENT" = "production" ] || [ "$ENVIRONMENT" = "staging" ]; then
    # Production
    # --------------------------------------------------

    echo "Running in production mode"

    # gunicorn w/ uvicorn workers (for ASGI)
    exec gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
fi
