# Generated by Django 5.1.7 on 2025-04-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roast',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='roast',
            name='is_selected',
            field=models.BooleanField(default=False, help_text='True if the roast is funny and should make it to the MasterRoast, False otherwise.'),
        ),
        migrations.AlterField(
            model_name='round',
            name='state',
            field=models.CharField(choices=[('UPLOAD_PHOTO', 'Upload Photo'), ('SHOW_ROAST_TARGET_ROULETTE', 'Show Roast Target Roulette'), ('SELECT_ROASTS', 'Select Roasts for Master Roast'), ('SHOW_MASTER_ROAST', 'Show Master Roast')], default='UPLOAD_PHOTO', help_text='Current state of this round.', max_length=26),
        ),
    ]
