# Generated by Django 5.1.7 on 2025-04-23 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_roast_is_approved_roast_is_selected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roast',
            name='round',
            field=models.ForeignKey(help_text='The round this roast contribution belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='roasts', to='games.round'),
        ),
    ]
